### ISSUE TITLE
Liquid Ajax Cart x PJAX

### ISSUE THREAD

**Issue by haroldao** [EvgeniyMukhamedjanov/liquid-ajax-cart#15]
It seems like Liquid Ajax Cart is not working with PJAX libraries👀

**Comment by haroldao** [comment]
I use "Operator" https://github.com/estrattonbailey/operator with Shopify Theme Lab https://github.com/uicrooks/shopify-theme-lab

**Comment by haroldao** [comment]
I don't use Slater but you can see Operator here (https://github.com/the-couch/slater/blob/master/packages/theme/src/scripts/router.js)

**Comment by haroldao** [comment]
![image](https://user-images.githubusercontent.com/36776278/161811785-3626dee6-8853-483b-b9fe-11ca61405ed1.png)
Here's what I've got in my console

**Comment by EvgeniyMukhamedjanov** [comment]
Hey @haroldao . Can you guide me how can I replicate this issue on my local computer?
So as I understand I need to install the "shopify-theme-lab" theme, then install the "operator". Then I need to see the code how do you use the operator and Liquid Ajax Cart.
Btw does this issue disappear if you remove the "operator" ?

**Comment by haroldao** [comment]
😮😮😮... yes I still have the error message @EvgeniyMukhamedjanov 
Here's the file where I imported L.A.C

![image](https://user-images.githubusercontent.com/36776278/161823686-dfe4a391-7be5-4948-9360-ac0e3f733f2a.png)

**Comment by haroldao** [comment]
![image](https://user-images.githubusercontent.com/36776278/161824124-88c16605-6a27-41ec-8a8e-fdf4183c4350.png)

**Comment by EvgeniyMukhamedjanov** [comment]
Yeah, for sure it is not related to the Operator or any other package. It should be a problem with Webpack/Module system. I'll install the shopify-theme-lab tomorrow and try to import LAC. For now you can include LAC as you did it on the previous project — using <script type="module">. After I find out what is the issue -- I let you know and you install LAC using npm again.
Can you also tell me if you did any changes in the "package.json" or any config files and if they are different from the current shopify-theme-lab repository?

**Comment by haroldao** [comment]
No I didn't. You're good to go.🙌🏽

**Comment by haroldao** [comment]
Side note : It's almost working (with your "manual" solution).... but when we change the page it's not working anymore since we have to "reload" the JS each time a page transition happens

**Comment by EvgeniyMukhamedjanov** [comment]
Hey @haroldao , I guess I found what was the issue. Can you please try if the updated version works for you:
https://github.com/EvgeniyMukhamedjanov/liquid-ajax-cart/blob/dev/docs/releases/liquid-ajax-cart-v1.10.1.js

Just download the file and put it next to the main.js and include it like this:
```
import './liquid-ajax-cart-v1.10.1.js';
```
and check if it works for you.

Please pay attention that Liquid Ajax Cart apply CSS classes to the `body` tag. It means if your PJAX root Element is `body` tag then after page change the classes will be missed. If it is the case then I can add an option to LAC to apply classes to the `html` tag. 

Once all is good I'll upload the v1.10.1 to npm as well.

**Comment by haroldao** [comment]
yeah it's working well ✅.

Okay that's fine. I'll get rid of PJAX for this project then.

**Comment by EvgeniyMukhamedjanov** [comment]
@haroldao 
Why do you want to get rid of PJAX? LAC should work well with PJAX because LAC listens only document events thus you can change DOM as you want.
Does LAC work after PJAX page change?

**Comment by haroldao** [comment]
no it's not working.

here's a quick example : When I click a button (to open the cart drawer) and I change the page, the class js-car-open is still set on the body

**Comment by EvgeniyMukhamedjanov** [comment]
@haroldao 
Aha. So it means that your PJAX root element is not body but under it.
What if you subscribe to the page change event (i think it is possible) and remove the `js-cart-open` class on every page change. I think it should be the only problem. All the other LAC classes depend on the cart state and shouldn't be changed after page change.

**Comment by EvgeniyMukhamedjanov** [comment]
Hey @haroldao 
I've just updated the npm version, so you can remove the local file and install it from npm.
Let me know if it works for you and I'll close the issue then :-)

**Comment by haroldao** [comment]
thank you man✨🙌🏽
