### ISSUE TITLE
The cart ajax is break when Shopify Markets is turned on.

### ISSUE THREAD

**Issue by tonybastienricher** [EvgeniyMukhamedjanov/liquid-ajax-cart#24]
The cart ajax doesn't work when you change the language of the site with Shopify Markets is turned on.

Example : 
https://pimentio.myshopify.com/
https://pimentio.myshopify.com/en

When I add a product via the English site to the cart, I get this error :

`Uncaught TypeError: can't access property "setActiveElement", this.cartNotification is null`

I think Shopify released new url cart routes.

**Comment by tonybastienricher** [comment]
Finally, it's a home-made mistake! 
If you have a problem with the URL from market, fixed the action in liquid form.

`{%- form 'product', product, id: product_form_id, class: 'form', novalidate: 'novalidate', action:'/cart/add', data-type: 'add-to-cart-form' -%}`

**Comment by EvgeniyMukhamedjanov** [comment]
@tonybastienricher 
Hey, I've just added Markets support. It is in the v1.10.2.
Hope it is not too late :-)

**Comment by EvgeniyMukhamedjanov** [comment]
If you update to the new version, pls don't hardcode the cart routes (like /cart/add for ex), use the routes that are provided by Shopify, because new Liquid Ajax Cart handle them.

**Comment by Julien-FLEXY** [comment]
Hey I have the same problem using the latest version. I'm not sure what is the error because I have no errors displayed but when I change the language or the country and I click on my add to cart button, it redirects me to the cart page. Any idea or things I should check please?

Thank you very much in advance !

**Comment by Julien-FLEXY** [comment]
Problem solved. To anyone who encounter this problem too : I was using self made form (<form action="/cart/add" ...) that I replaced by the shopify form tag ({% form "product"...) and everything is working now

**Comment by EvgeniyMukhamedjanov** [comment]
Hi @Julien-FLEXY ,
Yeah, if when the markets are on, all the system Shopify routes has prefixes, including add to cart forms.
