### ISSUE TITLE
add_to_cart event fires twice

### ISSUE THREAD

**Issue by driespieters** [EvgeniyMukhamedjanov/liquid-ajax-cart#64]
I noticed the add_to_cart event fire twice. This happens on Shopify's UA integration, the new GA4 integration and Shopify's custom pixel manager. 

To replicate add this code to the Customer event pixels:
`analytics.subscribe("product_added_to_cart", async (event) => {
console.log('Add to cart event')
});`

If I switch theme to Dawn it's not longer happening.

I think it has something to do with doing a update.js call after the add.js call when adding a product to cart.

**Comment by EvgeniyMukhamedjanov** [comment]
Hi @driespieters 
I appreciate that you reached out to me!
I've created a custom pixel with the code you provided on the [Liquid Ajax Cart Demo](https://liquid-ajax-cart.myshopify.com/) website (password: liquid-ajax-cart), and I can see only one "console.log" appeared at a time. The pixel is still there, so you can check it out as well.
I'm thinking maybe you use a theme that already have "ajax add to cart" functionality and there are two "add.js" happen at the same time -- one from theme, another one from liquid-ajax-cart? Shopify has this bug or feature :-), when you have two add.js requests at the same time, it ignores one of them, but pixel won't ignore.
So can we check the Network tab in the browser to make sure that there is only one add.js request at a time?

<img width="1079" alt="image" src="https://user-images.githubusercontent.com/13817355/230574397-ae76670e-d3eb-479b-8eeb-7bc68a96e83a.png">
<img width="1256" alt="image" src="https://user-images.githubusercontent.com/13817355/230574661-ebf330d4-16af-437c-8bc5-460e8c3d85b5.png">

**Comment by driespieters** [comment]
Hi @EvgeniyMukhamedjanov , Thanks for the fast response!

Would you mind checking the demo site again? I'm getting the event firing twice here as well. (Below 100 usd)

<img width="1470" alt="Scherm­afbeelding 2023-04-07 om 10 58 44" src="https://user-images.githubusercontent.com/5103134/230578919-049e6709-50e2-4985-898b-f1e0fc511829.png">

**Comment by EvgeniyMukhamedjanov** [comment]
@driespieters 
I noticed it happens on product page all the time, but not on the home page (at least for me) and this is very much strange, I still can't see the reason why it is happening, I need to spend some time to figure it out. Thank you very much for pointing out this bug.

Another thing I noticed, as I mentioned, I don't see two console.log message on the main page, but the thing is the message appears only after the cart is updated, that means the analytic event gets triggered by updates.js, not add.js and this is even more frightening than two messages :-) 

I'll also try to find the info on how the analytic works under the hood, if you have any, please share as well :-)

**Comment by EvgeniyMukhamedjanov** [comment]
@driespieters 
I've released a new version with the fixed issue. Could you check it out pls if it works for you?

**Comment by driespieters** [comment]
@EvgeniyMukhamedjanov 
That's great! Thank you for the very fast intervention and all the work on this module!
