### ISSUE TITLE
Compatibility of the Ajax Cart with "Gift Card Add Recipient" feature

### ISSUE THREAD

**Issue by thagxt** [EvgeniyMukhamedjanov/liquid-ajax-cart#75]
I'm curious about the compatibility of the ajax cart with the recently mandated feature, "Gift card add recipient". How does the Ajax Cart handle this? For reference, see [Dawn's implementation](https://github.com/Shopify/dawn/pull/2412).

Thank you for any insights!

**Comment by EvgeniyMukhamedjanov** [comment]
@thagxt 
Sorry, missed the issue.
So the new gift card feature is just a set of product form fields with the "properties[...]" names. 
These kind of fields have been supported from the 1st version of Liquid Ajax Cart :-)
