### ISSUE TITLE
ajax add to cart for bundles not working

### ISSUE THREAD

**Issue by klupsky** [EvgeniyMukhamedjanov/liquid-ajax-cart#97]
i have the following issue: add to cart for normal products works. 
only when using the free shopify bundle app, when i add the bundle to the cart, i get the error: `The bundle product '...' cannot be added to the cart.` and it is not. added to the cart. when i refresh the page, i can see the bundle was added to the cart.

**Comment by EvgeniyMukhamedjanov** [comment]
Hi @klupsky 
I don't have access to the repository you shared,
could you pls share a preview link of the free bundle PDP I'll check it?

**Comment by klupsky** [comment]
thank you, @EvgeniyMukhamedjanov i already "resolved" this issue, it seems to appear only when i run the prioject on localhost. when i open the shopify theme from the shopify online stores, it works.
